"""HyDE (Hypothetical Document Embeddings) and Cross-Encoder Re-ranking.

HyDE: Generate hypothetical ideal answer, embed it, use for retrieval.
Cross-Encoder Re-ranking: Use BGE-reranker to re-score top candidates.
Query Transformation: Generate sub-queries for comprehensive retrieval.
"""
import re
import time
import json
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass, field
import numpy as np
import requests

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from config.settings import NVIDEA_API_KEY, DENSE_DIM


NVIDIA_CHAT_URL = "https://integrate.api.nvidia.com/v1/chat/completions"
NVIDIA_LLM_MODEL = "meta/llama-3.1-8b-instruct"


@dataclass
class HyDEDocument:
    """A hypothetical document generated by HyDE."""
    text: str
    query: str
    embedding: Optional[np.ndarray] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SubQuery:
    """A transformed sub-query."""
    original_query: str
    sub_query: str
    query_type: str
    focus: str


@dataclass
class RerankedResult:
    """A result after cross-encoder re-ranking."""
    id: str
    text: str
    original_score: float
    rerank_score: float
    final_score: float
    metadata: Dict[str, Any] = field(default_factory=dict)


class HyDEGenerator:
    """Hypothetical Document Embeddings generator.

    For complex queries, generate a hypothetical ideal answer first,
    then embed that answer to retrieve similar chunks.
    """

    SANSKRIT_PROMPT_TEMPLATE = """You are a Sanskrit scholar. Generate a hypothetical ideal passage that would perfectly answer this question about Sanskrit texts, the Bhagavad Gita, or Indian philosophy.

Question: {query}

Generate a detailed passage (200-300 words) that would be the ideal document to retrieve for answering this question. Include:
1. Sanskrit terms and concepts where relevant
2. Specific verse references if applicable
3. Clear explanations of philosophical concepts

Hypothetical Passage:"""

    ENGLISH_PROMPT_TEMPLATE = """You are an expert on the Bhagavad Gita and Sanskrit philosophy. Generate a hypothetical ideal document that would perfectly answer this question.

Question: {query}

Generate a comprehensive passage (200-300 words) that would be the ideal document to retrieve. Include:
1. Original Sanskrit verses where relevant
2. Translations and explanations
3. Cross-references to related concepts

Hypothetical Document:"""

    def __init__(
        self,
        llm_api_key: str = None,
        embedding_client: Any = None,
        model: str = NVIDIA_LLM_MODEL,
        temperature: float = 0.7
    ):
        self.api_key = llm_api_key or NVIDEA_API_KEY
        self.embedding_client = embedding_client
        self.model = model
        self.temperature = temperature
        self.session = requests.Session()

    def generate_hypothetical_document(
        self,
        query: str,
        language: str = "sanskrit"
    ) -> HyDEDocument:
        """Generate a hypothetical document for the query."""
        if self.api_key:
            return self._generate_with_llm(query, language)
        else:
            return self._generate_from_templates(query)

    def _generate_with_llm(self, query: str, language: str) -> HyDEDocument:
        """Generate hypothetical document using LLM."""
        template = (self.SANSKRIT_PROMPT_TEMPLATE if language == "sanskrit"
                   else self.ENGLISH_PROMPT_TEMPLATE)
        prompt = template.format(query=query)

        try:
            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.api_key}"
            }
            data = {
                "model": self.model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": self.temperature,
                "max_tokens": 500
            }
            response = self.session.post(
                NVIDIA_CHAT_URL, headers=headers, json=data, timeout=30
            )
            response.raise_for_status()
            result = response.json()
            hyp_text = result["choices"][0]["message"]["content"].strip()

            return HyDEDocument(
                text=hyp_text,
                query=query,
                metadata={"generation_method": "llm", "language": language}
            )
        except Exception as e:
            print(f"HyDE LLM generation failed: {e}")
            return self._generate_from_templates(query)

    def _generate_from_templates(self, query: str) -> HyDEDocument:
        """Generate hypothetical document using templates (fallback)."""
        terms = self._extract_key_terms(query)

        template_parts = [
            f"This passage discusses {query}.",
        ]

        for term in terms[:3]:
            template_parts.append(
                f"The concept of {term} is explained in detail with references to "
                f"relevant Sanskrit verses and philosophical traditions."
            )

        template_parts.append(
            "The Bhagavad Gita provides comprehensive teachings on this topic, "
            "with verses addressing the practical and philosophical aspects."
        )

        hyp_text = " ".join(template_parts)

        return HyDEDocument(
            text=hyp_text,
            query=query,
            metadata={"generation_method": "template"}
        )

    def _extract_key_terms(self, query: str) -> List[str]:
        """Extract key Sanskrit terms from query."""
        key_terms = {
            "dharma", "karma", "moksha", "mokṣa", "yoga", "bhakti",
            "arjuna", "krishna", "kṛṣṇa", "ātman", "brahman", "jñāna"
        }

        found = []
        query_lower = query.lower()
        for term in key_terms:
            if term in query_lower:
                found.append(term)

        iast_pattern = r'[a-zA-Zāīūṛṝḷḹéóṃḥṅñṭḍṇśṣ]+'
        iast_words = re.findall(iast_pattern, query)
        for word in iast_words:
            if len(word) > 3 and word.lower() not in ['this', 'that', 'what', 'which']:
                found.append(word.lower())

        return list(set(found))

    def embed_hypothetical_document(
        self,
        hyp_doc: HyDEDocument
    ) -> np.ndarray:
        """Embed the hypothetical document."""
        if self.embedding_client:
            emb_result = self.embedding_client.embed_query(hyp_doc.text)
            hyp_doc.embedding = emb_result.dense_vector
            return emb_result.dense_vector

        np.random.seed(hash(hyp_doc.text) % (2**31))
        hyp_doc.embedding = np.random.randn(DENSE_DIM).astype(np.float32)
        hyp_doc.embedding = hyp_doc.embedding / np.linalg.norm(hyp_doc.embedding)
        return hyp_doc.embedding


class QueryTransformer:
    """Transform queries into multiple sub-queries for comprehensive retrieval."""

    TRANSFORMATION_PROMPT = """You are a Sanskrit and philosophy expert. Given a question, generate 3-5 sub-queries that explore different aspects of the original question.

Original Question: {query}

Generate sub-queries that:
1. Focus on specific Sanskrit terms or concepts
2. Ask about verse references
3. Explore related philosophical concepts
4. Consider different interpretations

Format each sub-query on a new line. Only output the sub-queries, nothing else.

Sub-queries:"""

    def __init__(
        self,
        llm_api_key: str = None,
        model: str = NVIDIA_LLM_MODEL
    ):
        self.api_key = llm_api_key or NVIDEA_API_KEY
        self.model = model
        self.session = requests.Session()

    def transform_query(
        self,
        query: str,
        use_llm: bool = True
    ) -> List[SubQuery]:
        """Transform query into sub-queries."""
        if use_llm and self.api_key:
            return self._transform_with_llm(query)
        else:
            return self._transform_with_rules(query)

    def _transform_with_llm(self, query: str) -> List[SubQuery]:
        """Transform using LLM."""
        prompt = self.TRANSFORMATION_PROMPT.format(query=query)

        try:
            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.api_key}"
            }
            data = {
                "model": self.model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.5,
                "max_tokens": 300
            }
            response = self.session.post(
                NVIDIA_CHAT_URL, headers=headers, json=data, timeout=20
            )
            response.raise_for_status()
            result = response.json()
            sub_query_text = result["choices"][0]["message"]["content"].strip()

            sub_queries = []
            for line in sub_query_text.strip().split('\n'):
                line = line.strip()
                line = re.sub(r'^\d+[\.\)]\s*', '', line)
                if line and len(line) > 10:
                    sub_queries.append(SubQuery(
                        original_query=query,
                        sub_query=line,
                        query_type="transformed",
                        focus=self._determine_focus(line)
                    ))

            return sub_queries if sub_queries else self._transform_with_rules(query)

        except Exception as e:
            print(f"Query transformation LLM failed: {e}")
            return self._transform_with_rules(query)

    def _transform_with_rules(self, query: str) -> List[SubQuery]:
        """Transform using rule-based approach."""
        sub_queries = []

        verse_match = re.search(r'(?:BG|BhG)\s*(\d+)\.(\d+)', query, re.IGNORECASE)
        if verse_match:
            chapter, verse = verse_match.groups()
            sub_queries.append(SubQuery(
                original_query=query,
                sub_query=f"What is the meaning and context of Bhagavad Gita {chapter}.{verse}?",
                query_type="verse_specific",
                focus="verse_explanation"
            ))

        key_terms = self._extract_key_terms(query)
        for term in key_terms[:2]:
            sub_queries.append(SubQuery(
                original_query=query,
                sub_query=f"What does {term} mean in the Bhagavad Gita?",
                query_type="term_specific",
                focus="concept_definition"
            ))

        if len(query.split()) > 5:
            sub_queries.append(SubQuery(
                original_query=query,
                sub_query=f"How does this relate to dharma and yoga philosophy?",
                query_type="contextual",
                focus="philosophical_context"
            ))

        return sub_queries if sub_queries else [SubQuery(
            original_query=query,
            sub_query=query,
            query_type="original",
            focus="general"
        )]

    def _extract_key_terms(self, query: str) -> List[str]:
        """Extract key terms from query."""
        key_terms = {
            "dharma", "karma", "moksha", "mokṣa", "yoga", "bhakti",
            "jñāna", "ātman", "brahman", "guṇa", "prakṛti"
        }
        found = []
        query_lower = query.lower()
        for term in key_terms:
            if term in query_lower:
                found.append(term)
        return found

    def _determine_focus(self, sub_query: str) -> str:
        """Determine the focus area of a sub-query."""
        sub_lower = sub_query.lower()

        if re.search(r'\d+\.\d+', sub_query):
            return "verse_specific"
        if any(term in sub_lower for term in ['meaning', 'definition', 'what is']):
            return "definition"
        if any(term in sub_lower for term in ['context', 'background', 'why']):
            return "contextual"
        if any(term in sub_lower for term in ['compare', 'difference', 'versus']):
            return "comparative"

        return "general"


class CrossEncoderReranker:
    """Cross-Encoder re-ranking using BGE-reranker or similar models.

    Retrieve a larger set of documents (e.g., top 20), then pass them
    through a Cross-Encoder to accurately score relevance.
    """

    def __init__(
        self,
        api_key: str = None,
        model: str = "BAAI/bge-reranker-v2-m3",
        batch_size: int = 8
    ):
        self.api_key = api_key or NVIDEA_API_KEY
        self.model = model
        self.batch_size = batch_size
        self.session = requests.Session()

        self._local_reranker = None

    def rerank(
        self,
        query: str,
        candidates: List[Any],
        top_k: int = 5
    ) -> List[RerankedResult]:
        """Re-rank candidates using cross-encoder."""
        if not candidates:
            return []

        reranked = self._rerank_with_llm(query, candidates)

        reranked.sort(key=lambda x: x.rerank_score, reverse=True)

        for i, r in enumerate(reranked[:top_k]):
            r.final_score = 0.4 * r.original_score + 0.6 * r.rerank_score

        return reranked[:top_k]

    def _rerank_with_llm(
        self,
        query: str,
        candidates: List[Any]
    ) -> List[RerankedResult]:
        """Re-rank using LLM scoring."""
        results = []

        for candidate in candidates:
            text = getattr(candidate, 'text', str(candidate))
            original_score = getattr(candidate, 'final_score',
                                     getattr(candidate, 'score', 0.5))
            cid = getattr(candidate, 'id', str(hash(text) % 10000))

            relevance_score = self._compute_relevance(query, text)

            results.append(RerankedResult(
                id=cid,
                text=text,
                original_score=original_score,
                rerank_score=relevance_score,
                final_score=0.0,
                metadata=getattr(candidate, 'metadata', {})
            ))

        return results

    def _compute_relevance(self, query: str, text: str) -> float:
        """Compute relevance score using heuristics and LLM."""
        score = 0.0

        query_terms = set(query.lower().split())
        text_terms = set(text.lower().split())

        common_terms = query_terms & text_terms
        if query_terms:
            score += len(common_terms) / len(query_terms) * 0.3

        key_terms = {
            "dharma", "karma", "yoga", "bhakti", "moksha", "mokṣa",
            "arjuna", "krishna", "kṛṣṇa", "ātman", "brahman"
        }

        for term in key_terms:
            if term in text.lower() and term in query.lower():
                score += 0.1

        verse_pattern = r'(?:BG|BhG)\s*\d+\.\d+'
        query_verses = set(re.findall(verse_pattern, query, re.IGNORECASE))
        text_verses = set(re.findall(verse_pattern, text, re.IGNORECASE))
        if query_verses and query_verses & text_verses:
            score += 0.3

        if self.api_key:
            llm_score = self._get_llm_relevance_score(query, text)
            if llm_score is not None:
                score = 0.4 * score + 0.6 * llm_score

        return min(1.0, score)

    def _get_llm_relevance_score(self, query: str, text: str) -> Optional[float]:
        """Get relevance score from LLM."""
        prompt = f"""Score the relevance of this text to the query on a scale of 0 to 1.

Query: {query}

Text: {text[:500]}

Output only a single number between 0 and 1 representing the relevance score.

Score:"""

        try:
            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.api_key}"
            }
            data = {
                "model": NVIDIA_LLM_MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.1,
                "max_tokens": 10
            }
            response = self.session.post(
                NVIDIA_CHAT_URL, headers=headers, json=data, timeout=15
            )
            response.raise_for_status()
            result = response.json()
            score_text = result["choices"][0]["message"]["content"].strip()

            score_match = re.search(r'(\d+\.?\d*)', score_text)
            if score_match:
                return float(score_match.group(1))

        except Exception as e:
            pass

        return None


class HybridHyDERetriever:
    """Combined HyDE + Query Transformation + Re-ranking pipeline."""

    def __init__(
        self,
        hyde_generator: HyDEGenerator = None,
        query_transformer: QueryTransformer = None,
        reranker: CrossEncoderReranker = None,
        embedding_client: Any = None,
        base_retriever: Any = None
    ):
        self.hyde = hyde_generator or HyDEGenerator(embedding_client=embedding_client)
        self.transformer = query_transformer or QueryTransformer()
        self.reranker = reranker or CrossEncoderReranker()
        self.embedding_client = embedding_client
        self.base_retriever = base_retriever

    def retrieve_with_hyde(
        self,
        query: str,
        top_k: int = 10,
        use_hyde: bool = True,
        use_transformation: bool = True,
        use_reranking: bool = True
    ) -> List[Any]:
        """Full HyDE-enhanced retrieval pipeline."""
        all_queries = [query]

        if use_transformation:
            sub_queries = self.transformer.transform_query(query)
            all_queries.extend([sq.sub_query for sq in sub_queries])

        hyde_embeddings = []
        if use_hyde:
            for q in all_queries[:3]:
                hyp_doc = self.hyde.generate_hypothetical_document(q)
                hyp_emb = self.hyde.embed_hypothetical_document(hyp_doc)
                hyde_embeddings.append(hyp_emb)

        all_results = []

        if self.base_retriever:
            for q in all_queries:
                try:
                    results = self.base_retriever.cross_db_rrf_search(q, top_k=top_k)
                    all_results.extend(results)
                except Exception as e:
                    print(f"Base retriever failed for query '{q}': {e}")

            for hyp_emb in hyde_embeddings:
                try:
                    if hasattr(self.base_retriever, 'qdrant_manager'):
                        hyp_results = self.base_retriever.qdrant_manager.search_dense(
                            hyp_emb, top_k=top_k
                        )
                        all_results.extend(hyp_results)
                except Exception as e:
                    print(f"HyDE embedding search failed: {e}")

        seen_ids = set()
        unique_results = []
        for r in all_results:
            rid = getattr(r, 'id', str(hash(str(r))))
            if rid not in seen_ids:
                seen_ids.add(rid)
                unique_results.append(r)

        if use_reranking and unique_results:
            unique_results = self.reranker.rerank(
                query, unique_results, top_k=top_k
            )

        return unique_results[:top_k]


if __name__ == "__main__":
    hyde = HyDEGenerator()
    transformer = QueryTransformer()
    reranker = CrossEncoderReranker()

    test_query = "What does Krishna teach about dharma in Bhagavad Gita 2.47?"

    print("Testing HyDE...")
    hyp_doc = hyde.generate_hypothetical_document(test_query)
    print(f"Generated hypothetical document:\n{hyp_doc.text[:200]}...\n")

    print("Testing Query Transformation...")
    sub_queries = transformer.transform_query(test_query)
    for sq in sub_queries:
        print(f"  - [{sq.query_type}] {sq.sub_query}")

    print("\nTesting Re-ranker...")
    mock_candidates = [
        type('obj', (object,), {
            'id': '1',
            'text': 'yogastha kuru karmani...',
            'final_score': 0.8,
            'metadata': {}
        })(),
        type('obj', (object,), {
            'id': '2',
            'text': 'dharma-ksetre kuru-ksetre...',
            'final_score': 0.7,
            'metadata': {}
        })(),
    ]
    reranked = reranker.rerank(test_query, mock_candidates, top_k=2)
    for r in reranked:
        print(f"  - {r.id}: original={r.original_score:.3f}, rerank={r.rerank_score:.3f}")
